PLOTS_SHOW = True
PLOTS_SAVE = False
PLOTS_PREFIX = '001'
PLOTS_INTERVAL = [0, 0] # [0, 0] will plot’em all

TIME_UNITS_PER_YEAR = 360
MONTH = int(TIME_UNITS_PER_YEAR / 12)
YEAR = TIME_UNITS_PER_YEAR

ITERATIONS = TIME_UNITS_PER_YEAR * 4

NUM_CHICKS = 100
NUM_ACTIVE_CHICKS_PER_STEP = int(NUM_CHICKS / 10)
INITIAL_AMOUNT = 10000

BOND_STOKEN_ISSUANCE_RATE = 0.002 # per iteration
EXTERNAL_YIELD = 0.05 # 5%, annualized

INITIAL_PRICE = 25.0
TWAP_PERIOD = 20 # iterations

# number of iterations to take the average APR of the AMM
AMM_APR_PERIOD = 10 # iterations
AMM_FEE = 0.04 / 100 # 0.04%
MAX_SLIPPAGE = 0.03 # 3%
AMM_ARBITRAGE_DIVERGENCE = 0.01 # 5%

REDEMPTION_ARBITRAGE_DIVERGENCE = 0.01 # 5%

#natural rate
INITIAL_NATURAL_RATE = 0.05 # annualized
SD_NATURAL_RATE = 0.002

CHICKEN_IN_GAMMA_SHAPE = 2.0
CHICKEN_IN_GAMMA_SCALE = 0.1
CHICKEN_OUT_PROBABILITY = 0.1
CHICKEN_UP_PROBABILITY = 0.5
CHICKEN_IN_AMM_SHARE = 0.2 # 20%
CHICKEN_IN_AMM_MAX_SHARE = 0.5 # 50%
